import { PageIndicator } from "@/components/page-indicator";
import ScreenSizeTracker from "@/components/screen-size";
import { Toaster } from "@/components/ui/sonner";
import { TanstackProvider } from "@/providers/tanstack-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Geologica } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geologica.variable} antialiased`}
      >
        <TanstackProvider>
          {children}
          <ScreenSizeTracker />
          <PageIndicator />
          <Toaster />
        </TanstackProvider>
      </body>
    </html>
  );
}
